name: Deploy

on:
  push:
    branches:
      - main     # Deploys to production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST_DEVCENTRIC }}
          username: ${{ secrets.DO_USER_DEVCENTRIC }}
          key: ${{ secrets.SSH_PRIVATE_KEY_DEVCENTRIC }}
          passphrase: ${{ secrets.SSH_PASSPHRASE_DEVCENTRIC }}
          port: 22
          script: |
            cd /home/forge/iot-test.online
            git stash
            git pull origin main
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan storage:link
            npm ci
            npm run build
            php artisan queue:restart
            php artisan optimize:clear
